name: 'Update Azure locations and product categories'

on:
  workflow_dispatch:

  schedule:
    # run every Saturday (UTC)
    - cron: '1 2 * * 6'

jobs:
  update-azure-data:
    runs-on: ubuntu-latest
    permissions:
      contents: write # to be able to publish a GitHub release
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          ref: dev
      - name: Update Azure locations and product categories
        run: |
          cd AzPC.Blazor/AzPC.Blazor/config/

          echo "Updating Azure locations..."
          curl https://btnguyen2k.github.io/azure-regions/locations.json -o azure-locations.json

          echo "Updating Azure product categories..."
          curl https://btnguyen2k.github.io/azure-regions/products.json -o azure-products.json

          echo $(date) > touch.txt

          echo "Committing changes..."
          git config --global user.email "<>"
          git config --global user.name "CI Build"
          git add azure-locations.json azure-products.json touch.txt
          git commit -m "Update Azure locations and product categories"
          git push origin dev

  BuildAndTest:
    runs-on: ubuntu-latest
    needs: update-azure-data
    strategy:
      matrix:
        dotnet: [ '8.x', '9.x' ]
    name: Build and test with dotnet ${{ matrix.dotnet }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          ref: dev
      - name: Setup dotnet ${{ matrix.dotnet }}
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: ${{ matrix.dotnet }}
      - name: Display dotnet version
        run: dotnet --version
      - name: Install dependencies
        run: dotnet restore
      - name: Build
        run: dotnet build --no-restore
      - name: Test
        run: dotnet test --no-restore

  TestDockerfileLinux:
    needs: BuildAndTest
    runs-on: ubuntu-latest
    strategy:
      matrix:
        platforms: [ 'linux/amd64', 'linux/arm64' ]
    name: Test building Docker image(s) for Linux
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          ref: dev
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      - name: Build Docker image for ${{ matrix.platforms }}
        uses: docker/build-push-action@v6
        with:
          platforms: ${{ matrix.platforms }}
          push: false
          tags: test
          file: ./Dockerfile
          context: ./
