name: 'Update Azure locations and product categories'

on:
  workflow_call:
  schedule:
    # run every Saturday (UTC)
    - cron: '1 2 * * 6'

jobs:
  update-azure-data:
    runs-on: ubuntu-latest
    permissions:
      contents: write # to be able to publish a GitHub release
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Update Azure locations and product categories
        run: |
          git checkout dev
          cd AzPC.Blazor/AzPC.Blazor/config/

          echo "Updating Azure locations..."
          curl https://btnguyen2k.github.io/azure-regions/locations.json -o azure-locations.json

          echo "Updating Azure product categories..."
          curl https://btnguyen2k.github.io/azure-regions/products.json -o azure-products.json

          echo "Committing changes..."
          git config --global user.email "<>"
          git config --global user.name "CI Build"
          git add azure-locations.json azure-products.json
          git commit -m "Update Azure locations and product categories"
          git push origin dev
